pipeline {
    agent any
    stages {
        stage('hello') {
            steps {
                script {
                    sh "echo 'Hello World'"
                }
            }
        }
    }
}
